# Generated by Django 5.2.16 on 2026-07-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
