# Generated by Django 5.2.16 on 2026-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
