# Generated by Django 5.2.16 on 2026-07-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_message_text_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text_message',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
