# Generated by Django 5.2.16 on 2026-07-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_remove_message_text_message_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
